---
title: "My Rmd Word document"
author: "LU"
date: "`r format(Sys.time(),'%d %B,%Y')`"
bibliography: citation.bib
fig_width: 6 
fig_height: 4 
output:
  tufte::tufte_html: default
  tufte::tufte_book:
    citation_package: natbib
    latex_engine: xelatex
  tufte::tufte_handout:
    citation_package: natbib
    latex_engine: xelatex
  html_document:
    df_print: paged
link-citations: yes
---

```{r, setup, echo = FALSE}
knitr::opts_chunk$set(
  warning = FALSE,
  message = FALSE,
  echo = TRUE,
  comment = "#>"
)
knitr::read_chunk("external_code.R")
source("external_code.R")
```


```{r, warning=FALSE, echo=FALSE}
library(tidyverse)
```

### This is a plot for starwars. 
```{r, starwars-plot, fig.cap = "A ggplot of starwars"}
starwars %>%
  filter(species == "Human") %>%
  ggplot() + 
  aes(x = height , y = eye_color) + geom_point()
```

### This is a table for starwars. 

```{r starwars-tbl}
starwars %>%
  filter(species == "Human") %>%
  select(name, height, homeworld) %>%
  knitr::kable(caption = "A knitr kable table of starwars data")
```

### This is a function used from external code. 
```{r, code_from_external}
res = sqrt_function(9)
res
```
```{r running_code, cache=TRUE}
x = c(1,2,3,4,5,6,7,8)
plot(sqrt_function(x))
```

### Citation 

This paper develops a generalization of the widely used difference‐in‐differences method for evaluating the effects of policy changes.[@athey2006identification]

Some people say that [@vadrevu2018intercomparison] while others 
[@athey2006identification]




